ALTER TABLE dbo.Item DROP COLUMN ToStr;

ALTER TABLE dbo.Raid DROP COLUMN ToStr;

ALTER TABLE dbo.Class DROP COLUMN ToStr;

ALTER TABLE dbo.Spec DROP COLUMN ToStr;

ALTER TABLE dbo.Player DROP COLUMN ToStr;
GO